### PR TITLE
Finalize modal styling and fix all bugs

### LINKED ISSUE #172: Modal styling for Benefits Cards
All on-page styling and functionality for benefit cards with modal / fragment / card link support is completed in https://github.com/aemsites/idfc/pull/149. The actual modal popups are using the boilerplate modal functionality and styling. 

Current:
Image

Target style:
Image

---

They all have the same background, but the blue cards have the same blue textured background for the modal content as they do on the cards.

Image

 The "pewter" color cards have a silver gradient background.

Image

### PR DESCRIPTION
**Pull request by roperev**
- Updated modal.css to support a page background image layered on top of the gradient backdrop when applicable.
- Modified modal.js to set a CSS custom property for the page background image and add a class to the dialog for styling purposes.
- Updated modal.css to improve the positioning and layering of decoration images within the modal.
- Modified modal.js to create and append decoration images as DOM elements, ensuring they are displayed in the top layer of the modal.

Fix #172 

Test URLs:
- Before: https://main--idfc--aemsites.aem.page/credit-card/metal-credit-card/mayura
- After: https://172-modalstyles--idfc--aemsites.aem.page/credit-card/metal-credit-card/mayura

Visual fixes:
image

image

### CODE REVIEW

File: blocks/modal/modal.js [hunk 1]
```diff
@@ -87,6 +88,23 @@ export async function createModal(contentNodes, options = {}) {
     bgImg.loading = 'eager';
 
     pageBackground.append(bgImg);
+
+    // Add decoration images as DOM elements (top-right and bottom-left)
+    // These go INSIDE the dialog to be in the top layer, but use fixed positioning
+    if (decorationImage) {
```
Comment (helms-charity) [inline blocks/modal/modal.js:94]: I like how you called it decor. I might want to rename my section doodles to decor for Sections at some point to keep things consistent...

**Review by helms-charity — APPROVED** [review]
